var items={
    starters:[
        {
            itemsname:'vegmanchchuria',
            itemprice:900,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'panner',
            itemprice:600,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'chilli-chicken',
            itemprice:800,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'chiken-lollipops',
            itemprice:500,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
    liquids:[
        {
            itemsname:'sambar',
            itemprice:600,
            quantity:1,
            quantityUnits:'liters'
        },
        {
            itemsname:'rasam',
            itemprice:300,
            quantity:1,
            quantityUnits:'liters'
        },
        {
            itemsname:'curd-chutney',
            itemprice:900,
            quantity:1,
            quantityUnits:'liters'
        },
        {
            itemsname:'gumadikay-pulusu',
            itemprice:1000,
            quantity:1,
            quantityUnits:'liters'
        },
    ],
    curries:[
        {
            itemsname:'tomato-dal',
            itemprice:400,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'potato',
            itemprice:500,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'panner-curry',
            itemprice:1000,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'chicken',
            itemprice:900,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
    rice:[
        {
            itemsname:'pulihora',
            itemprice:500,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'biryani',
            itemprice:600,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'tomato-rice',
            itemprice:700,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
    bread:[
        {
            itemsname:'roti',
            itemprice:600,
            quantity:1,
            quantityUnits:'kg'
        },  {
            itemsname:'nan',
            itemprice:700,
            quantity:1,
            quantityUnits:'kg'
        },
        {
            itemsname:'numali',
            itemprice:800,
            quantity:1,
            quantityUnits:'kg'
        },
    ],
}